### ISSUE TITLE
Tests do not build anymore with clang++-16 and newer.

### ISSUE THREAD

**Issue by piotrrak** [eyalz800/zpp_throwing#8]
Hi, Just so you know.

`zpp::throwing<void>` handling needs some rework.
Few other things can be revisited with newer clang/libc++ but thid is the major one.

**Comment by eyalz800** [comment]
Hi,

Thanks for reporting, can you be more specific / provide godbolt link for the issue/improvement?

I will check clang 16 soon. 

Thanks

**Comment by piotrrak** [comment]
Sorry for being terese and not very informative about the issue, was pretty late for me.

Right now you'll get with clang-16, clang-17, clang-18:

```
./include/../../zpp_throwing.h:1650:20: error: call to member function 'catch_exception_object' is ambiguous
 1650 |             return catch_exception_object(
      |                    ^~~~~~~~~~~~~~~~~~~~~~
./include/../../zpp_throwing.h:1720:54: note: in instantiation of function template specialization 'zpp::throwing<void>::catches<(lambda at src/destruction.cpp:183:12)>' requested here
 1720 |         return std::forward<TryClause>(try_clause)().catches(
      |                                                      ^
src/destruction.cpp:169:21: note: in instantiation of function template specialization 'zpp::try_catch<(lambda at src/destruction.cpp:169:31), (lambda at src/destruction.cpp:183:12)>' requested here
  169 |         return zpp::try_catch([&]() -> zpp::throwing<void> {
      |                     ^
./include/../../zpp_throwing.h:1363:9: note: candidate function [with Clause = (lambda at src/destruction.cpp:183:12), Clauses = <>, $2 = <>, CatchType = void, NonVoidCatchType = void, IsThrowing = true]
 1363 |         catch_exception_object(const dynamic_object & exception,
      |         ^
./include/../../zpp_throwing.h:1516:20: note: candidate function [with Clause = (lambda at src/destruction.cpp:183:12), Clauses = <>, $2 = <>, CatchType = void]
 1516 |     constexpr Type catch_exception_object(const dynamic_object & exception,
      |                    ^
src/destruction.cpp:169:16: error: no viable conversion from returned value of type 'void' to function return type 'zpp::throwing<void>'
  169 |         return zpp::try_catch([&]() -> zpp::throwing<void> {
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  170 |             trigger.trigger();
      |             ~~~~~~~~~~~~~~~~~~
  171 |             destruction_resource resource(is_resource_destroyed);
      |             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  172 |             EXPECT_EQ(is_resource_destroyed, false);
      |             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  173 |             EXPECT_EQ(is_exception_destroyed, false);
      |             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  174 | 
  175 |             co_await [&]() -> zpp::throwing<void> {
      |             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  176 |                 trigger.trigger();
      |                 ~~~~~~~~~~~~~~~~~~
  177 |                 co_yield destruction_exception(is_exception_destroyed);
      |                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  178 | 
  179 |                 [] { FAIL(); }();
      |                 ~~~~~~~~~~~~~~~~~
  180 |             }();
      |             ~~~~
  181 | 
  182 |             [] { FAIL(); }();
      |             ~~~~~~~~~~~~~~~~~
  183 |         }, [&]() -> zpp::throwing<void> {
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  184 |             trigger.trigger();
      |             ~~~~~~~~~~~~~~~~~~
./include/../../zpp_throwing.h:1142:21: note: candidate constructor (the implicit copy constructor) not viable: cannot convert argument of incomplete type 'void' to 'const throwing<void> &' for 1st argument
 1142 | class [[nodiscard]] throwing
      |                     ^~~~~~~~
./include/../../zpp_throwing.h:1142:21: note: candidate constructor (the implicit move constructor) not viable: cannot convert argument of incomplete type 'void' to 'throwing<void> &&' for 1st argument
 1142 | class [[nodiscard]] throwing
      |                     ^~~~~~~~
./include/../../zpp_throwing.h:1230:15: note: candidate constructor not viable: cannot convert argument of incomplete type 'void' to 'rethrow_t' for 1st argument
 1230 |     constexpr throwing(rethrow_t) noexcept
      |               ^        ~~~~~~~~~
./include/../../zpp_throwing.h:1197:15: note: candidate template ignored: substitution failure [with value:auto = void]: cannot form a reference to 'void'
 1197 |     constexpr throwing(std::convertible_to<Type> auto && value)
      |               ^                                       ~~
./include/../../zpp_throwing.h:1213:15: note: candidate template ignored: substitution failure [with value:auto = void]: cannot form a reference to 'void'
 1213 |     constexpr throwing(ThrowableThrough<promise_type> auto && value)
      |               ^                                            ~~
./include/../../zpp_throwing.h:1181:24: note: explicit constructor is not a candidate
 1181 |     constexpr explicit throwing(std::nullptr_t) noexcept
      |                        ^
./include/../../zpp_throwing.h:1189:24: note: explicit constructor is not a candidate
 1189 |     constexpr explicit throwing(promise_type & promise) noexcept
      |                        ^
2 errors generated.
make[1]: *** [zpp.mk:360: obj/debug/default/src/destruction.o] Błąd 1
make: *** [zpp.mk:69: build] Błąd 2
```

Please do note the however, the line numbers will differ as those are from my [fork](https://github.com/piotrrak/zpp_throwing).
You can see [all commented]() out tests that won't build, but all of those are affected but same problem.

As fork improvements those are things like:
- using `std::remove_cvref_t<>`
- Constraining for stateless allocators.
- using `__builtin_unreachable()`/c++23 `std::unreachable()` instead of UB in `suspend_destroying` awaitable
- reworking how allocator mixin
- etc.
Nothing major and some of those I can contribute back, case by case, once I'll get to closer shape of how I think it should look.

Right now I am refactoring code to simplify some conditional_t/requires expression templates.
Naming/splitting things so I am not get lost and on my way to switch to `std::coroutine_traits` rather than nested promise types.

Reworked bit mixin for promise type selection to open a way of getting things like adding support for stateful allocators bit easier.

Few other ideas are came to my mind while tinkering with it.
One of those that `throwing<>` template should be like `std::generator` and allow to specify both `Ref` and `Value` types.

My changes are working in progress and it is more convinient for me to work with what latest compilers support already in c++20 and readd fallbacks later on.

Slightly off-topic, just to give some context on how and why I plan to use zpp_throwing:

My usecase is bit uncommon and different than yours.
I've stummbled on legacy library code that builds `thread_local` stack of context (contextual stacktrace) for error handling:
```
 {
       Context c{"While doing Foo"};
       doFoo([]{ throw InternlError{"Foo couldn't be done";});
}
```
So in case of error you can get something akin to:
```
An internal error have occured 
    While doing Foo
Because: Foo couldn't be done.
```
It's nice but it won't mix well with coroutines the way it is.
I see the mechanics `zpp::throwing` as a way to make it work and keep this functionality while utilizing coroutines.
It will have some problems like special functions and how to mix with other coroutines, but it feels like it could be figured out.
But I plan to give it a shot to this experiment mostly out of curiosity.

Even more OT:

Another question, that I find interesting to anwser would be, if such eh strategy or some form of it is worthy candidate for SJLJ eh (setjump/longjump) replacement or alternative.
Coroutines optimizations will surely evolve event more and SJLJ doesn't seem to have much room for improvement.

**Comment by eyalz800** [comment]
For the test cases - Try now to compile with newer clang, I've added a fix in the main branch.

I'm reading to see if there is anything else to fix from your detailed comment, thank you for it.

What do you mean in "using __builtin_unreachable()/c++23 std::unreachable() instead of UB in suspend_destroying awaitable" - Do you think that right now there is a UB in suspend_destroy? I didn't quite understand.

"Right now I am refactoring code to simplify some conditional_t/requires expression templates.
Naming/splitting things so I am not get lost and on my way to switch to std::coroutine_traits rather than nested promise types." - that sounds nice, let me know when you can share how you did it. I rushed most of the concepts inline to be able to meet the timeline for the cppcon talk.

I'm closing this issue because the issue described in the title is fixed - let's keep discussing if you want about improvements here or elsewhere with more specific details.

**Comment by piotrrak** [comment]
Thanks for quick fix, I will try it ASAP.

wrt. UB I meant `suspend_destroy::await_resume()` sorry

```
            [[noreturn]] void await_resume() noexcept { while (true); }
```

 `while (true) {}` is itself the undefined behaviour - yes. Is it a big problem in this case in ie. [[noreturn]] function? I don't think so, but  `__builtin_unreachable()`  and added later added to c++ was invented for such cases as far I understand.
 
So  `while(true) {}` is just an UB which will likely be removed by codegen, because it is the UB. c++23 `std::unreachable()` is telling the compiler that this code won't be reached  with well defined behaviour.  I assumed it is what you meant in `suspend_destroy::await_resume()`. Difference between the is that with UB version you'll never know. But I can believe you've seen in godbolt what you wanted to see with `while(true) {}`.

If you meant spin forever for debugging or something, you'll need memory barrier inside the loop.
Something like `asm volatile("" ::: "memory")` would do and is fairly portable.

**Comment by piotrrak** [comment]
Yes, the fix does work. Thank you.

**Comment by eyalz800** [comment]
It's been enough time that I forgot that I have while (true), but I think I had std::unreachable in there originally and it just didn't produce the correct code. Maybe this was resolved with the improved compiler, worth checking. Anyway should this paper land - https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2023/p2809r0.html, it should not be a problem.
